/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puyecto;

import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin1
 */


public class empresa extends javax.swing.JFrame {

    private    conexion mysql=new conexion();
    private    Connection co=mysql.conectar();
    private String nombreusu;
    /**
     * Creates new form empresa
     * @param usuario
     */
    public empresa(String usuario) {
        initComponents();
        this.nombreusu = usuario;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PubliOferta = new javax.swing.JButton();
        ConsultarOferta = new javax.swing.JButton();
        AnalizarSolicitudes = new javax.swing.JButton();
        BuscarCandiPorCriterio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Empresa"));

        PubliOferta.setText("Publicar Oferta");
        PubliOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PubliOfertaActionPerformed(evt);
            }
        });

        ConsultarOferta.setText("Consultar Oferta");
        ConsultarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarOfertaActionPerformed(evt);
            }
        });

        AnalizarSolicitudes.setText("Analizar Solicitudes");
        AnalizarSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalizarSolicitudesActionPerformed(evt);
            }
        });

        BuscarCandiPorCriterio.setText("Buscar candidato por criterio");
        BuscarCandiPorCriterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarCandiPorCriterioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BuscarCandiPorCriterio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AnalizarSolicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PubliOferta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ConsultarOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConsultarOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PubliOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AnalizarSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BuscarCandiPorCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PubliOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PubliOfertaActionPerformed
       try {
                    Statement stm;
                    System.out.println(nombreusu);
                    stm = co.createStatement();
                    
                    ResultSet rs = stm.executeQuery("SELECT * FROM datos_empresa WHERE nombreusu='"+nombreusu+"'");
                    System.out.println("");
                    String CIF="";
                    while (rs.next()){
                    CIF=rs.getString(2);
                    }
                    
                    //Abre la ventana para ver la oferta mas detallada.
                    publicar_oferta v = new publicar_oferta(CIF, nombreusu);
                    v.setVisible(true);
                    this.dispose();//Cierra la ventana en la que estas actualmente.
                    
                } catch (SQLException ex) {
                    Logger.getLogger(empresa.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_PubliOfertaActionPerformed

    private void ConsultarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarOfertaActionPerformed
        // TODO add your handling code here:
        int cont=0;
        String CIF="";
                try {
                    Statement stm;
                    stm = co.createStatement();
                    
                    ResultSet rs = stm.executeQuery("SELECT * FROM datos_empresa WHERE nombreusu='"+nombreusu+"'");
                    while (rs.next()){
                    CIF=rs.getString(2);
                    }
                    Statement stm1 = co.createStatement();
                    ResultSet rs1 = stm1.executeQuery("SELECT COUNT(codigo_oferta) FROM ofertas_empleo WHERE CIF='"+CIF+"'");
                    while(rs.next()){
                        if(rs.getInt(1)!=0){
                           cont = rs1.getInt(1);
                        }
                    }
                    if(cont==0){
                        JOptionPane.showMessageDialog(null, "No tienes ofertas publicadas actualmente."); 
                    }
                    else{
                    //Abre la ventana para ver la oferta mas detallada.
                    con_oferta v = new con_oferta(CIF, nombreusu);
                    v.setVisible(true);
                    this.dispose();//Cierra la ventana en la que estas actualmente.
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(empresa.class.getName()).log(Level.SEVERE, null, ex);
                }
        
    }//GEN-LAST:event_ConsultarOfertaActionPerformed

    private void AnalizarSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalizarSolicitudesActionPerformed
        try {
                    Statement stm;
                    System.out.println(nombreusu);
                    stm = co.createStatement();
                    
                    ResultSet rs = stm.executeQuery("SELECT * FROM datos_empresa WHERE nombreusu='"+nombreusu+"'");
                    String CIF="";
                    while (rs.next()){
                    CIF=rs.getString(2);
                    }
                    
                    //Abre la ventana para ver la oferta mas detallada.
                    analizarSolicitudes v = new analizarSolicitudes(CIF, nombreusu);
                    v.setVisible(true);
                    this.dispose();//Cierra la ventana en la que estas actualmente.
                    
                } catch (SQLException ex) {
                    Logger.getLogger(empresa.class.getName()).log(Level.SEVERE, null, ex);
                }
        
    }//GEN-LAST:event_AnalizarSolicitudesActionPerformed

    private void BuscarCandiPorCriterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCandiPorCriterioActionPerformed
                    buscarcandidatos v = new buscarcandidatos(nombreusu);
                    v.setVisible(true);
                    this.dispose();
        
    }//GEN-LAST:event_BuscarCandiPorCriterioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empresa("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalizarSolicitudes;
    private javax.swing.JButton BuscarCandiPorCriterio;
    private javax.swing.JButton ConsultarOferta;
    private javax.swing.JButton PubliOferta;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
