/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puyecto;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin1
 */
public class RegistrarseEmp extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarseEmp
     */
    public RegistrarseEmp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisEmp = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        CIF = new javax.swing.JLabel();
        Direccion_Postal = new javax.swing.JLabel();
        Telefono = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        Contacto = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();
        NombreText = new javax.swing.JTextField();
        CIFText = new javax.swing.JTextField();
        DireccionText = new javax.swing.JTextField();
        TelefonoText = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        ContactoText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        NuevoUsuario = new javax.swing.JLabel();
        NuevoUsuarioText = new javax.swing.JTextField();
        Contrasena = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RegisEmp.setText("REGISTRO DE EMPRESA");

        Nombre.setText("Nombre:");

        CIF.setText("CIF:");

        Direccion_Postal.setText("Direccion Postal:");

        Telefono.setText("Telefono:");

        Email.setText("E-mail");

        Descripcion.setText("Descripcion:");

        Contacto.setText("Contato:");

        Atras.setText("Atras");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        Siguiente.setText("Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        NuevoUsuario.setText("Nuevo Usuario:");

        Contrasena.setText("Contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(RegisEmp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nombre)
                                    .addComponent(CIF)
                                    .addComponent(Direccion_Postal)
                                    .addComponent(Telefono)
                                    .addComponent(Email)
                                    .addComponent(Contacto)
                                    .addComponent(Descripcion)
                                    .addComponent(NuevoUsuario)
                                    .addComponent(Contrasena))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ContactoText, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TelefonoText, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(EmailText)
                                    .addComponent(DireccionText)
                                    .addComponent(NombreText, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(CIFText)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(NuevoUsuarioText)
                                    .addComponent(jPasswordField1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Atras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Siguiente)))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegisEmp)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(NombreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CIF)
                    .addComponent(CIFText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direccion_Postal)
                    .addComponent(DireccionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono)
                    .addComponent(TelefonoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Descripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Contacto)
                    .addComponent(ContactoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NuevoUsuario)
                    .addComponent(NuevoUsuarioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contrasena)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atras)
                    .addComponent(Siguiente))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        BienvenidoEmp p=new BienvenidoEmp();
            p.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_AtrasActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
conexion mysql=new conexion();
        Connection co=mysql.conectar();

        String cif,email,nombre, descripcion, contacto,nombreusu, contraseña;
       int telefono, direccion;
       try{
       email=EmailText.getText();
       
       nombre=NombreText.getText();
       direccion=Integer.parseInt(DireccionText.getText());
       telefono=Integer.parseInt(TelefonoText.getText());
       cif=CIFText.getText();
       descripcion=jTextArea1.getText();
       contacto=ContactoText.getText();
       nombreusu=NuevoUsuarioText.getText();
       contraseña=jPasswordField1.getText();

       String tipo="empresa";
               String sentenciaSQL;
        sentenciaSQL="INSERT INTO datos_empresa (nombre, cif, telefono, email, direccion_postal, descripcion, contacto, nombreusu)"
                +"VALUES(?,?,?,?,?,?,?,?)";
               String sentenciaSQL2;
        sentenciaSQL2="INSERT INTO usuarios (nombreusu, clave, tipo)"+
                "VALUES(?,?,?)";
        
        try {
            PreparedStatement psp2 =co.prepareStatement(sentenciaSQL2);
            psp2.setString(1, nombreusu);
            psp2.setString(2, contraseña);
            psp2.setString(3, tipo);
            int m=0,n=0;
            try{
            m=psp2.executeUpdate();

            PreparedStatement psp =co.prepareStatement(sentenciaSQL);
            psp.setString(1, nombre);
            psp.setString(2, cif);
            psp.setInt(3, telefono);
            psp.setString(4, email);
            psp.setInt(5, direccion);
            psp.setString(6, descripcion);
            psp.setString(7, contacto);
            psp.setString(8, nombreusu);
            
            n=psp.executeUpdate();
            }catch (com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException ea){
                JOptionPane.showMessageDialog(null, "Ya existe ese usuario");
            }
            if (n>0&&m>0){
                JOptionPane.showMessageDialog(null, "Datos guardados correctamente");
                IniciarSesionEmp p=new IniciarSesionEmp();
                p.setVisible(true);
                this.dispose();

            }
            else {
                JOptionPane.showMessageDialog(null, "Error");

            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistrarseCan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       }catch(java.lang.NumberFormatException ea){
            JOptionPane.showMessageDialog(null, "Telefono introducido incorrectamente");
                  
            }
    }//GEN-LAST:event_SiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarseEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarseEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarseEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarseEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarseEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JLabel CIF;
    private javax.swing.JTextField CIFText;
    private javax.swing.JLabel Contacto;
    private javax.swing.JTextField ContactoText;
    private javax.swing.JLabel Contrasena;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JTextField DireccionText;
    private javax.swing.JLabel Direccion_Postal;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailText;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreText;
    private javax.swing.JLabel NuevoUsuario;
    private javax.swing.JTextField NuevoUsuarioText;
    private javax.swing.JLabel RegisEmp;
    private javax.swing.JButton Siguiente;
    private javax.swing.JLabel Telefono;
    private javax.swing.JTextField TelefonoText;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
